package builtin

const (
	CommandCat         = "cat"
	CommandDate        = "date"
	CommandEcho        = "echo"
	CommandEnv         = "env"
	CommandFind        = "find"
	CommandFrontmatter = "frontmatter"
	CommandGrep        = "grep"
	CommandRG          = "rg"
	CommandHead        = "head"
	CommandJSON        = "json"
	CommandLS          = "ls"
	CommandMounts      = "mounts"
	CommandTree        = "tree"
	CommandMan         = "man"
	CommandSed         = "sed"
	CommandTail        = "tail"
	CommandTee         = "tee"

	CommandMkdir = "mkdir"
	CommandCp    = "cp"
	CommandMv    = "mv"
	CommandRm    = "rm"
	CommandRmdir = "rmdir"
	CommandTouch = "touch"
	CommandCd    = "cd"
	CommandPwd   = "pwd"
	CommandWhich = "which"
	CommandType  = "type"
	CommandWc    = "wc"
	CommandSort  = "sort"
	CommandUniq  = "uniq"
	CommandDiff  = "diff"

	CommandEdit     = "edit"
	CommandGlob     = "glob"
	CommandView     = "view"
	CommandDirname  = "dirname"
	CommandBasename = "basename"
)
